name: "Clean the old docker images"

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: "21 21 * * *"  # Scheduled run

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      REGISTRY: ghcr.io

    steps:
      - name: Set REPO environment variable
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Delete 'PR' containers older than a week
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          image-names: ${{ env.REGISTRY }}/${{ env.REPO }}
          token: ${{ secrets.GH_REPO_TOKEN }}
          image-tags: "pr*"  # target any image that has a tag starting with the word test or dev
          # image-tags: "!latest"
          cut-off: 2w 3d
          dry-run: true

